// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.7
#pragma warning disable
global using global::System;
global using global::System.Buffers;
global using global::System.Buffers.Binary;
global using global::System.Buffers.Text;
global using global::System.CodeDom;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Frozen;
global using global::System.Collections.Generic;
global using global::System.Collections.Immutable;
global using global::System.Collections.ObjectModel;
global using global::System.Collections.Specialized;
global using global::System.ComponentModel;
global using global::System.ComponentModel.DataAnnotations;
global using global::System.ComponentModel.DataAnnotations.Schema;
global using global::System.ComponentModel.Design;
global using global::System.ComponentModel.Design.Serialization;
global using global::System.Composition;
global using global::System.Composition.Convention;
global using global::System.Composition.Debugging;
global using global::System.Composition.Diagnostics;
global using global::System.Composition.Hosting;
global using global::System.Composition.Hosting.Core;
global using global::System.Composition.Hosting.Providers;
global using global::System.Composition.Hosting.Providers.CurrentScope;
global using global::System.Composition.Hosting.Providers.ExportFactory;
global using global::System.Composition.Hosting.Providers.ImportMany;
global using global::System.Composition.Hosting.Providers.Lazy;
global using global::System.Composition.Hosting.Providers.Metadata;
global using global::System.Composition.Hosting.Util;
global using global::System.Composition.Runtime;
global using global::System.Composition.Runtime.Util;
global using global::System.Composition.TypedParts;
global using global::System.Composition.TypedParts.ActivationFeatures;
global using global::System.Composition.TypedParts.Discovery;
global using global::System.Composition.TypedParts.Util;
global using global::System.Configuration;
global using global::System.Configuration.Assemblies;
global using global::System.Configuration.Internal;
global using global::System.Configuration.Provider;
global using global::System.Data;
global using global::System.Data.Common;
global using global::System.Data.Odbc;
global using global::System.Data.OleDb;
global using global::System.Data.Sql;
global using global::System.Data.SqlClient;
global using global::System.Data.SqlTypes;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Diagnostics.Contracts;
global using global::System.Diagnostics.Eventing;
global using global::System.Diagnostics.Eventing.Reader;
global using global::System.Diagnostics.Metrics;
global using global::System.Diagnostics.PerformanceData;
global using global::System.Diagnostics.SymbolStore;
global using global::System.Diagnostics.Tracing;
global using global::System.Drawing;
global using global::System.Drawing.Configuration;
global using global::System.Drawing.Design;
global using global::System.Drawing.Drawing2D;
global using global::System.Drawing.Imaging;
global using global::System.Drawing.Printing;
global using global::System.Drawing.Text;
global using global::System.Dynamic;
global using global::System.Formats;
global using global::System.Formats.Asn1;
global using global::System.Formats.Tar;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Compression;
global using global::System.IO.Enumeration;
global using global::System.IO.Hashing;
global using global::System.IO.IsolatedStorage;
global using global::System.IO.MemoryMappedFiles;
global using global::System.IO.Packaging;
global using global::System.IO.Pipelines;
global using global::System.IO.Pipes;
global using global::System.IO.Ports;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Media;
global using global::System.Net;
global using global::System.Net.Cache;
global using global::System.Net.Http;
global using global::System.Net.Http.Headers;
global using global::System.Net.Http.Json;
global using global::System.Net.Http.Metrics;
global using global::System.Net.Mail;
global using global::System.Net.Mime;
global using global::System.Net.NetworkInformation;
global using global::System.Net.PeerToPeer;
global using global::System.Net.PeerToPeer.Collaboration;
global using global::System.Net.Quic;
global using global::System.Net.Security;
global using global::System.Net.Sockets;
global using global::System.Net.WebSockets;
global using global::System.Numerics;
global using global::System.Numerics.Hashing;
global using global::System.Reflection;
global using global::System.Reflection.Emit;
global using global::System.Reflection.Metadata;
global using global::System.Reflection.Metadata.Ecma335;
global using global::System.Reflection.PortableExecutable;
global using global::System.Resources;
global using global::System.Runtime;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.ConstrainedExecution;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.InteropServices;
global using global::System.Runtime.InteropServices.ComTypes;
global using global::System.Runtime.InteropServices.JavaScript;
global using global::System.Runtime.InteropServices.Marshalling;
global using global::System.Runtime.InteropServices.ObjectiveC;
global using global::System.Runtime.InteropServices.Swift;
global using global::System.Runtime.Intrinsics;
global using global::System.Runtime.Intrinsics.Arm;
global using global::System.Runtime.Intrinsics.Wasm;
global using global::System.Runtime.Intrinsics.X86;
global using global::System.Runtime.Loader;
global using global::System.Runtime.Remoting;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.Serialization.DataContracts;
global using global::System.Runtime.Serialization.Formatters;
global using global::System.Runtime.Serialization.Formatters.Binary;
global using global::System.Runtime.Serialization.Json;
global using global::System.Runtime.Versioning;
global using global::System.Security;
global using global::System.Security.AccessControl;
global using global::System.Security.Authentication;
global using global::System.Security.Authentication.ExtendedProtection;
global using global::System.Security.Claims;
global using global::System.Security.Cryptography;
global using global::System.Security.Cryptography.Pkcs;
global using global::System.Security.Cryptography.X509Certificates;
global using global::System.Security.Cryptography.Xml;
global using global::System.Security.Permissions;
global using global::System.Security.Policy;
global using global::System.Security.Principal;
global using global::System.ServiceModel;
global using global::System.ServiceModel.Syndication;
global using global::System.ServiceProcess;
global using global::System.Text;
global using global::System.Text.Encodings;
global using global::System.Text.Encodings.Web;
global using global::System.Text.Json;
global using global::System.Text.Json.Nodes;
global using global::System.Text.Json.Schema;
global using global::System.Text.Json.Serialization;
global using global::System.Text.Json.Serialization.Metadata;
global using global::System.Text.RegularExpressions;
global using global::System.Text.RegularExpressions.Generated;
global using global::System.Text.Unicode;
global using global::System.Threading;
global using global::System.Threading.Channels;
global using global::System.Threading.Tasks;
global using global::System.Threading.Tasks.Dataflow;
global using global::System.Threading.Tasks.Sources;
global using global::System.Timers;
global using global::System.Transactions;
global using global::System.Web;
global using global::System.Windows;
global using global::System.Windows.Input;
global using global::System.Windows.Markup;
global using global::System.Xml;
global using global::System.Xml.Linq;
global using global::System.Xml.Resolvers;
global using global::System.Xml.Schema;
global using global::System.Xml.Serialization;
global using global::System.Xml.XPath;
global using global::System.Xml.Xsl;
global using global::CommunityToolkit;
global using global::CommunityToolkit.Common;
global using global::CommunityToolkit.Common.Collections;
global using global::CommunityToolkit.Common.Deferred;
global using global::CommunityToolkit.Common.Extensions;
global using global::CommunityToolkit.Common.Helpers;
global using global::CommunityToolkit.Diagnostics;
global using global::CommunityToolkit.Helpers;
global using global::CommunityToolkit.HighPerformance;
global using global::CommunityToolkit.HighPerformance.Buffers;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces;
global using global::CommunityToolkit.HighPerformance.Buffers.Views;
global using global::CommunityToolkit.HighPerformance.Enumerables;
global using global::CommunityToolkit.HighPerformance.Helpers;
global using global::CommunityToolkit.HighPerformance.Helpers.Internals;
global using global::CommunityToolkit.HighPerformance.Memory;
global using global::CommunityToolkit.HighPerformance.Memory.Internals;
global using global::CommunityToolkit.HighPerformance.Memory.Views;
global using global::CommunityToolkit.HighPerformance.Streams;
global using global::DotNetProjectFile;
global using global::DotNetProjectFile.Analyzers;
global using global::DotNetProjectFile.Analyzers.EditorConfig;
global using global::DotNetProjectFile.Analyzers.Generic;
global using global::DotNetProjectFile.Analyzers.Helpers;
global using global::DotNetProjectFile.Analyzers.Ini;
global using global::DotNetProjectFile.Analyzers.MsBuild;
global using global::DotNetProjectFile.Analyzers.Resx;
global using global::DotNetProjectFile.Analyzers.Slnx;
global using global::DotNetProjectFile.BuildAgents;
global using global::DotNetProjectFile.Caching;
global using global::DotNetProjectFile.CodeAnalysis;
global using global::DotNetProjectFile.Collections;
global using global::DotNetProjectFile.Conversion;
global using global::DotNetProjectFile.Diagnostics;
global using global::DotNetProjectFile.EditorConfig;
global using global::DotNetProjectFile.Git;
global using global::DotNetProjectFile.IO;
global using global::DotNetProjectFile.Ini;
global using global::DotNetProjectFile.Licensing;
global using global::DotNetProjectFile.MsBuild;
global using global::DotNetProjectFile.MsBuild.CSharp;
global using global::DotNetProjectFile.MsBuild.Conversion;
global using global::DotNetProjectFile.MsBuild.VisualBasic;
global using global::DotNetProjectFile.Navigation;
global using global::DotNetProjectFile.NuGet;
global using global::DotNetProjectFile.NuGet.Packaging;
global using global::DotNetProjectFile.Parsing;
global using global::DotNetProjectFile.Parsing.Internal;
global using global::DotNetProjectFile.Resx;
global using global::DotNetProjectFile.Slnx;
global using global::DotNetProjectFile.Syntax;
global using global::DotNetProjectFile.Text;
global using global::DotNetProjectFile.Text.Globbing;
global using global::DotNetProjectFile.Xml;
global using global::Emik;
global using global::Emik.Morsels;
global using global::Fody;
global using global::FxResources;
global using global::FxResources.System;
global using global::FxResources.System.Composition;
global using global::FxResources.System.Composition.Convention;
global using global::FxResources.System.Composition.Hosting;
global using global::FxResources.System.Composition.Runtime;
global using global::FxResources.System.Composition.TypedParts;
global using global::Grammr;
global using global::Grammr.Lexers;
global using global::Grammr.Parsers;
global using global::Grammr.Syntax;
global using global::Grammr.Text;
global using global::ILMerge;
global using global::InlineIL;
global using global::InlineMethod;
global using global::JetBrains;
global using global::JetBrains.Annotations;
global using global::LocalsInit;
global using global::Microsoft;
global using global::Microsoft.CSharp;
global using global::Microsoft.CSharp.RuntimeBinder;
global using global::Microsoft.Cci;
global using global::Microsoft.Cci.Pdb;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.CodeAnalysis.AddImport;
global using global::Microsoft.CodeAnalysis.CaseCorrection;
global using global::Microsoft.CodeAnalysis.ChangeNamespace;
global using global::Microsoft.CodeAnalysis.Classification;
global using global::Microsoft.CodeAnalysis.Classification.Classifiers;
global using global::Microsoft.CodeAnalysis.CodeActions;
global using global::Microsoft.CodeAnalysis.CodeCleanup;
global using global::Microsoft.CodeAnalysis.CodeCleanup.Providers;
global using global::Microsoft.CodeAnalysis.CodeFixes;
global using global::Microsoft.CodeAnalysis.CodeFixesAndRefactorings;
global using global::Microsoft.CodeAnalysis.CodeGen;
global using global::Microsoft.CodeAnalysis.CodeGeneration;
global using global::Microsoft.CodeAnalysis.CodeRefactorings;
global using global::Microsoft.CodeAnalysis.CodeStyle;
global using global::Microsoft.CodeAnalysis.Collections;
global using global::Microsoft.CodeAnalysis.Collections.Internal;
global using global::Microsoft.CodeAnalysis.Debugging;
global using global::Microsoft.CodeAnalysis.Diagnostics;
global using global::Microsoft.CodeAnalysis.Diagnostics.Analyzers;
global using global::Microsoft.CodeAnalysis.Diagnostics.Analyzers.NamingStyles;
global using global::Microsoft.CodeAnalysis.Diagnostics.Telemetry;
global using global::Microsoft.CodeAnalysis.Differencing;
global using global::Microsoft.CodeAnalysis.Editing;
global using global::Microsoft.CodeAnalysis.EditorConfig;
global using global::Microsoft.CodeAnalysis.EditorConfig.Parsing;
global using global::Microsoft.CodeAnalysis.EditorConfig.Parsing.NamingStyles;
global using global::Microsoft.CodeAnalysis.EmbeddedLanguages;
global using global::Microsoft.CodeAnalysis.EmbeddedLanguages.Common;
global using global::Microsoft.CodeAnalysis.EmbeddedLanguages.VirtualChars;
global using global::Microsoft.CodeAnalysis.Emit;
global using global::Microsoft.CodeAnalysis.Emit.EditAndContinue;
global using global::Microsoft.CodeAnalysis.Emit.NoPia;
global using global::Microsoft.CodeAnalysis.ErrorLogger;
global using global::Microsoft.CodeAnalysis.ErrorReporting;
global using global::Microsoft.CodeAnalysis.Extensions;
global using global::Microsoft.CodeAnalysis.ExternalAccess;
global using global::Microsoft.CodeAnalysis.ExternalAccess.Pythia;
global using global::Microsoft.CodeAnalysis.ExternalAccess.Pythia.Api;
global using global::Microsoft.CodeAnalysis.ExternalAccess.UnitTesting;
global using global::Microsoft.CodeAnalysis.ExternalAccess.UnitTesting.Api;
global using global::Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript;
global using global::Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript.Api;
global using global::Microsoft.CodeAnalysis.ExtractMethod;
global using global::Microsoft.CodeAnalysis.FindSymbols;
global using global::Microsoft.CodeAnalysis.FindSymbols.FindReferences;
global using global::Microsoft.CodeAnalysis.FindSymbols.Finders;
global using global::Microsoft.CodeAnalysis.FindSymbols.SymbolTree;
global using global::Microsoft.CodeAnalysis.FlowAnalysis;
global using global::Microsoft.CodeAnalysis.FlowAnalysis.SymbolUsageAnalysis;
global using global::Microsoft.CodeAnalysis.Formatting;
global using global::Microsoft.CodeAnalysis.Formatting.Rules;
global using global::Microsoft.CodeAnalysis.GeneratedCodeRecognition;
global using global::Microsoft.CodeAnalysis.Host;
global using global::Microsoft.CodeAnalysis.Host.Mef;
global using global::Microsoft.CodeAnalysis.Indentation;
global using global::Microsoft.CodeAnalysis.InitializeParameter;
global using global::Microsoft.CodeAnalysis.Internal;
global using global::Microsoft.CodeAnalysis.Internal.Log;
global using global::Microsoft.CodeAnalysis.InternalUtilities;
global using global::Microsoft.CodeAnalysis.Interop;
global using global::Microsoft.CodeAnalysis.LanguageService;
global using global::Microsoft.CodeAnalysis.LanguageService.TypeInferenceService;
global using global::Microsoft.CodeAnalysis.MoveDeclarationNearReference;
global using global::Microsoft.CodeAnalysis.NamingStyles;
global using global::Microsoft.CodeAnalysis.Notification;
global using global::Microsoft.CodeAnalysis.ObsoleteSymbol;
global using global::Microsoft.CodeAnalysis.Operations;
global using global::Microsoft.CodeAnalysis.Options;
global using global::Microsoft.CodeAnalysis.OrganizeImports;
global using global::Microsoft.CodeAnalysis.Packaging;
global using global::Microsoft.CodeAnalysis.PatternMatching;
global using global::Microsoft.CodeAnalysis.PooledObjects;
global using global::Microsoft.CodeAnalysis.Precedence;
global using global::Microsoft.CodeAnalysis.Progress;
global using global::Microsoft.CodeAnalysis.ProjectSystem;
global using global::Microsoft.CodeAnalysis.ReassignedVariable;
global using global::Microsoft.CodeAnalysis.Recommendations;
global using global::Microsoft.CodeAnalysis.Remote;
global using global::Microsoft.CodeAnalysis.RemoveUnnecessaryImports;
global using global::Microsoft.CodeAnalysis.Rename;
global using global::Microsoft.CodeAnalysis.Rename.ConflictEngine;
global using global::Microsoft.CodeAnalysis.ReplaceDiscardDeclarationsWithAssignments;
global using global::Microsoft.CodeAnalysis.RuntimeMembers;
global using global::Microsoft.CodeAnalysis.SQLite;
global using global::Microsoft.CodeAnalysis.SQLite.Interop;
global using global::Microsoft.CodeAnalysis.SQLite.v2;
global using global::Microsoft.CodeAnalysis.SQLite.v2.Interop;
global using global::Microsoft.CodeAnalysis.SemanticModelReuse;
global using global::Microsoft.CodeAnalysis.Serialization;
global using global::Microsoft.CodeAnalysis.Shared;
global using global::Microsoft.CodeAnalysis.Shared.CodeStyle;
global using global::Microsoft.CodeAnalysis.Shared.Collections;
global using global::Microsoft.CodeAnalysis.Shared.Extensions;
global using global::Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery;
global using global::Microsoft.CodeAnalysis.Shared.Helpers;
global using global::Microsoft.CodeAnalysis.Shared.Helpers.RemoveUnnecessaryImports;
global using global::Microsoft.CodeAnalysis.Shared.Naming;
global using global::Microsoft.CodeAnalysis.Shared.TestHooks;
global using global::Microsoft.CodeAnalysis.Shared.Utilities;
global using global::Microsoft.CodeAnalysis.Simplification;
global using global::Microsoft.CodeAnalysis.Simplification.Simplifiers;
global using global::Microsoft.CodeAnalysis.SolutionCrawler;
global using global::Microsoft.CodeAnalysis.SourceGeneration;
global using global::Microsoft.CodeAnalysis.SourceGeneratorTelemetry;
global using global::Microsoft.CodeAnalysis.Storage;
global using global::Microsoft.CodeAnalysis.SymbolDisplay;
global using global::Microsoft.CodeAnalysis.SymbolSearch;
global using global::Microsoft.CodeAnalysis.Symbols;
global using global::Microsoft.CodeAnalysis.Syntax;
global using global::Microsoft.CodeAnalysis.Syntax.InternalSyntax;
global using global::Microsoft.CodeAnalysis.Tags;
global using global::Microsoft.CodeAnalysis.TaskList;
global using global::Microsoft.CodeAnalysis.Telemetry;
global using global::Microsoft.CodeAnalysis.Text;
global using global::Microsoft.CodeAnalysis.UnitTests;
global using global::Microsoft.CodeAnalysis.Utilities;
global using global::Microsoft.CodeAnalysis.VisualBasic;
global using global::Microsoft.CodeAnalysis.VisualBasic.CodeGeneration;
global using global::Microsoft.CodeAnalysis.VisualBasic.CodeStyle;
global using global::Microsoft.CodeAnalysis.VisualBasic.Formatting;
global using global::Microsoft.CodeAnalysis.VisualBasic.Simplification;
global using global::Microsoft.CodeAnalysis.Workspaces;
global using global::Microsoft.CodeAnalysis.Workspaces.Diagnostics;
global using global::Microsoft.CodeAnalysis.Workspaces.ProjectSystem;
global using global::Microsoft.DiaSymReader;
global using global::Microsoft.SqlServer;
global using global::Microsoft.SqlServer.Server;
global using global::Microsoft.VisualBasic;
global using global::Microsoft.VisualBasic.CompilerServices;
global using global::Microsoft.VisualBasic.FileIO;
global using global::Microsoft.Win32;
global using global::Microsoft.Win32.SafeHandles;
global using global::Mono;
global using global::Mono.Cecil;
global using global::Mono.Cecil.Cil;
global using global::Mono.Cecil.Metadata;
global using global::Mono.Cecil.PE;
global using global::Mono.Cecil.Pdb;
global using global::Mono.Cecil.Rocks;
global using global::Mono.Collections;
global using global::Mono.Collections.Generic;
global using global::Mono.Security;
global using global::Mono.Security.Cryptography;
global using global::NullGuard;
global using global::NullGuard.CodeAnalysis;
global using global::Roslyn;
global using global::Roslyn.Utilities;
global using global::Scifa;
global using global::Scifa.CheckedExceptions;
global using global::Scifa.CheckedExceptions.Attributes;
global using global::StaticLambda;
global using global::StaticLambda.Fody;

// Polyfills of namespaces in case dependencies are conditional.
namespace System { }

namespace System.Buffers { }

namespace System.Buffers.Binary { }

namespace System.Buffers.Text { }

namespace System.CodeDom { }

namespace System.CodeDom.Compiler { }

namespace System.Collections { }

namespace System.Collections.Concurrent { }

namespace System.Collections.Frozen { }

namespace System.Collections.Generic { }

namespace System.Collections.Immutable { }

namespace System.Collections.ObjectModel { }

namespace System.Collections.Specialized { }

namespace System.ComponentModel { }

namespace System.ComponentModel.DataAnnotations { }

namespace System.ComponentModel.DataAnnotations.Schema { }

namespace System.ComponentModel.Design { }

namespace System.ComponentModel.Design.Serialization { }

namespace System.Composition { }

namespace System.Composition.Convention { }

namespace System.Composition.Debugging { }

namespace System.Composition.Diagnostics { }

namespace System.Composition.Hosting { }

namespace System.Composition.Hosting.Core { }

namespace System.Composition.Hosting.Providers { }

namespace System.Composition.Hosting.Providers.CurrentScope { }

namespace System.Composition.Hosting.Providers.ExportFactory { }

namespace System.Composition.Hosting.Providers.ImportMany { }

namespace System.Composition.Hosting.Providers.Lazy { }

namespace System.Composition.Hosting.Providers.Metadata { }

namespace System.Composition.Hosting.Util { }

namespace System.Composition.Runtime { }

namespace System.Composition.Runtime.Util { }

namespace System.Composition.TypedParts { }

namespace System.Composition.TypedParts.ActivationFeatures { }

namespace System.Composition.TypedParts.Discovery { }

namespace System.Composition.TypedParts.Util { }

namespace System.Configuration { }

namespace System.Configuration.Assemblies { }

namespace System.Configuration.Internal { }

namespace System.Configuration.Provider { }

namespace System.Data { }

namespace System.Data.Common { }

namespace System.Data.Odbc { }

namespace System.Data.OleDb { }

namespace System.Data.Sql { }

namespace System.Data.SqlClient { }

namespace System.Data.SqlTypes { }

namespace System.Diagnostics { }

namespace System.Diagnostics.CodeAnalysis { }

namespace System.Diagnostics.Contracts { }

namespace System.Diagnostics.Eventing { }

namespace System.Diagnostics.Eventing.Reader { }

namespace System.Diagnostics.Metrics { }

namespace System.Diagnostics.PerformanceData { }

namespace System.Diagnostics.SymbolStore { }

namespace System.Diagnostics.Tracing { }

namespace System.Drawing { }

namespace System.Drawing.Configuration { }

namespace System.Drawing.Design { }

namespace System.Drawing.Drawing2D { }

namespace System.Drawing.Imaging { }

namespace System.Drawing.Printing { }

namespace System.Drawing.Text { }

namespace System.Dynamic { }

namespace System.Formats { }

namespace System.Formats.Asn1 { }

namespace System.Formats.Tar { }

namespace System.Globalization { }

namespace System.IO { }

namespace System.IO.Compression { }

namespace System.IO.Enumeration { }

namespace System.IO.Hashing { }

namespace System.IO.IsolatedStorage { }

namespace System.IO.MemoryMappedFiles { }

namespace System.IO.Packaging { }

namespace System.IO.Pipelines { }

namespace System.IO.Pipes { }

namespace System.IO.Ports { }

namespace System.Linq { }

namespace System.Linq.Expressions { }

namespace System.Media { }

namespace System.Net { }

namespace System.Net.Cache { }

namespace System.Net.Http { }

namespace System.Net.Http.Headers { }

namespace System.Net.Http.Json { }

namespace System.Net.Http.Metrics { }

namespace System.Net.Mail { }

namespace System.Net.Mime { }

namespace System.Net.NetworkInformation { }

namespace System.Net.PeerToPeer { }

namespace System.Net.PeerToPeer.Collaboration { }

namespace System.Net.Quic { }

namespace System.Net.Security { }

namespace System.Net.Sockets { }

namespace System.Net.WebSockets { }

namespace System.Numerics { }

namespace System.Numerics.Hashing { }

namespace System.Reflection { }

namespace System.Reflection.Emit { }

namespace System.Reflection.Metadata { }

namespace System.Reflection.Metadata.Ecma335 { }

namespace System.Reflection.PortableExecutable { }

namespace System.Resources { }

namespace System.Runtime { }

namespace System.Runtime.CompilerServices { }

namespace System.Runtime.ConstrainedExecution { }

namespace System.Runtime.ExceptionServices { }

namespace System.Runtime.InteropServices { }

namespace System.Runtime.InteropServices.ComTypes { }

namespace System.Runtime.InteropServices.JavaScript { }

namespace System.Runtime.InteropServices.Marshalling { }

namespace System.Runtime.InteropServices.ObjectiveC { }

namespace System.Runtime.InteropServices.Swift { }

namespace System.Runtime.Intrinsics { }

namespace System.Runtime.Intrinsics.Arm { }

namespace System.Runtime.Intrinsics.Wasm { }

namespace System.Runtime.Intrinsics.X86 { }

namespace System.Runtime.Loader { }

namespace System.Runtime.Remoting { }

namespace System.Runtime.Serialization { }

namespace System.Runtime.Serialization.DataContracts { }

namespace System.Runtime.Serialization.Formatters { }

namespace System.Runtime.Serialization.Formatters.Binary { }

namespace System.Runtime.Serialization.Json { }

namespace System.Runtime.Versioning { }

namespace System.Security { }

namespace System.Security.AccessControl { }

namespace System.Security.Authentication { }

namespace System.Security.Authentication.ExtendedProtection { }

namespace System.Security.Claims { }

namespace System.Security.Cryptography { }

namespace System.Security.Cryptography.Pkcs { }

namespace System.Security.Cryptography.X509Certificates { }

namespace System.Security.Cryptography.Xml { }

namespace System.Security.Permissions { }

namespace System.Security.Policy { }

namespace System.Security.Principal { }

namespace System.ServiceModel { }

namespace System.ServiceModel.Syndication { }

namespace System.ServiceProcess { }

namespace System.Text { }

namespace System.Text.Encodings { }

namespace System.Text.Encodings.Web { }

namespace System.Text.Json { }

namespace System.Text.Json.Nodes { }

namespace System.Text.Json.Schema { }

namespace System.Text.Json.Serialization { }

namespace System.Text.Json.Serialization.Metadata { }

namespace System.Text.RegularExpressions { }

namespace System.Text.RegularExpressions.Generated { }

namespace System.Text.Unicode { }

namespace System.Threading { }

namespace System.Threading.Channels { }

namespace System.Threading.Tasks { }

namespace System.Threading.Tasks.Dataflow { }

namespace System.Threading.Tasks.Sources { }

namespace System.Timers { }

namespace System.Transactions { }

namespace System.Web { }

namespace System.Windows { }

namespace System.Windows.Input { }

namespace System.Windows.Markup { }

namespace System.Xml { }

namespace System.Xml.Linq { }

namespace System.Xml.Resolvers { }

namespace System.Xml.Schema { }

namespace System.Xml.Serialization { }

namespace System.Xml.XPath { }

namespace System.Xml.Xsl { }

namespace CommunityToolkit { }

namespace CommunityToolkit.Common { }

namespace CommunityToolkit.Common.Collections { }

namespace CommunityToolkit.Common.Deferred { }

namespace CommunityToolkit.Common.Extensions { }

namespace CommunityToolkit.Common.Helpers { }

namespace CommunityToolkit.Diagnostics { }

namespace CommunityToolkit.Helpers { }

namespace CommunityToolkit.HighPerformance { }

namespace CommunityToolkit.HighPerformance.Buffers { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces { }

namespace CommunityToolkit.HighPerformance.Buffers.Views { }

namespace CommunityToolkit.HighPerformance.Enumerables { }

namespace CommunityToolkit.HighPerformance.Helpers { }

namespace CommunityToolkit.HighPerformance.Helpers.Internals { }

namespace CommunityToolkit.HighPerformance.Memory { }

namespace CommunityToolkit.HighPerformance.Memory.Internals { }

namespace CommunityToolkit.HighPerformance.Memory.Views { }

namespace CommunityToolkit.HighPerformance.Streams { }

namespace DotNetProjectFile { }

namespace DotNetProjectFile.Analyzers { }

namespace DotNetProjectFile.Analyzers.EditorConfig { }

namespace DotNetProjectFile.Analyzers.Generic { }

namespace DotNetProjectFile.Analyzers.Helpers { }

namespace DotNetProjectFile.Analyzers.Ini { }

namespace DotNetProjectFile.Analyzers.MsBuild { }

namespace DotNetProjectFile.Analyzers.Resx { }

namespace DotNetProjectFile.Analyzers.Slnx { }

namespace DotNetProjectFile.BuildAgents { }

namespace DotNetProjectFile.Caching { }

namespace DotNetProjectFile.CodeAnalysis { }

namespace DotNetProjectFile.Collections { }

namespace DotNetProjectFile.Conversion { }

namespace DotNetProjectFile.Diagnostics { }

namespace DotNetProjectFile.EditorConfig { }

namespace DotNetProjectFile.Git { }

namespace DotNetProjectFile.IO { }

namespace DotNetProjectFile.Ini { }

namespace DotNetProjectFile.Licensing { }

namespace DotNetProjectFile.MsBuild { }

namespace DotNetProjectFile.MsBuild.CSharp { }

namespace DotNetProjectFile.MsBuild.Conversion { }

namespace DotNetProjectFile.MsBuild.VisualBasic { }

namespace DotNetProjectFile.Navigation { }

namespace DotNetProjectFile.NuGet { }

namespace DotNetProjectFile.NuGet.Packaging { }

namespace DotNetProjectFile.Parsing { }

namespace DotNetProjectFile.Parsing.Internal { }

namespace DotNetProjectFile.Resx { }

namespace DotNetProjectFile.Slnx { }

namespace DotNetProjectFile.Syntax { }

namespace DotNetProjectFile.Text { }

namespace DotNetProjectFile.Text.Globbing { }

namespace DotNetProjectFile.Xml { }

namespace Emik { }

namespace Emik.Morsels { }

namespace Fody { }

namespace FxResources { }

namespace FxResources.System { }

namespace FxResources.System.Composition { }

namespace FxResources.System.Composition.Convention { }

namespace FxResources.System.Composition.Hosting { }

namespace FxResources.System.Composition.Runtime { }

namespace FxResources.System.Composition.TypedParts { }

namespace Grammr { }

namespace Grammr.Lexers { }

namespace Grammr.Parsers { }

namespace Grammr.Syntax { }

namespace Grammr.Text { }

namespace ILMerge { }

namespace InlineIL { }

namespace InlineMethod { }

namespace JetBrains { }

namespace JetBrains.Annotations { }

namespace LocalsInit { }

namespace Microsoft { }

namespace Microsoft.CSharp { }

namespace Microsoft.CSharp.RuntimeBinder { }

namespace Microsoft.Cci { }

namespace Microsoft.Cci.Pdb { }

namespace Microsoft.CodeAnalysis { }

namespace Microsoft.CodeAnalysis.AddImport { }

namespace Microsoft.CodeAnalysis.CaseCorrection { }

namespace Microsoft.CodeAnalysis.ChangeNamespace { }

namespace Microsoft.CodeAnalysis.Classification { }

namespace Microsoft.CodeAnalysis.Classification.Classifiers { }

namespace Microsoft.CodeAnalysis.CodeActions { }

namespace Microsoft.CodeAnalysis.CodeCleanup { }

namespace Microsoft.CodeAnalysis.CodeCleanup.Providers { }

namespace Microsoft.CodeAnalysis.CodeFixes { }

namespace Microsoft.CodeAnalysis.CodeFixesAndRefactorings { }

namespace Microsoft.CodeAnalysis.CodeGen { }

namespace Microsoft.CodeAnalysis.CodeGeneration { }

namespace Microsoft.CodeAnalysis.CodeRefactorings { }

namespace Microsoft.CodeAnalysis.CodeStyle { }

namespace Microsoft.CodeAnalysis.Collections { }

namespace Microsoft.CodeAnalysis.Collections.Internal { }

namespace Microsoft.CodeAnalysis.Debugging { }

namespace Microsoft.CodeAnalysis.Diagnostics { }

namespace Microsoft.CodeAnalysis.Diagnostics.Analyzers { }

namespace Microsoft.CodeAnalysis.Diagnostics.Analyzers.NamingStyles { }

namespace Microsoft.CodeAnalysis.Diagnostics.Telemetry { }

namespace Microsoft.CodeAnalysis.Differencing { }

namespace Microsoft.CodeAnalysis.Editing { }

namespace Microsoft.CodeAnalysis.EditorConfig { }

namespace Microsoft.CodeAnalysis.EditorConfig.Parsing { }

namespace Microsoft.CodeAnalysis.EditorConfig.Parsing.NamingStyles { }

namespace Microsoft.CodeAnalysis.EmbeddedLanguages { }

namespace Microsoft.CodeAnalysis.EmbeddedLanguages.Common { }

namespace Microsoft.CodeAnalysis.EmbeddedLanguages.VirtualChars { }

namespace Microsoft.CodeAnalysis.Emit { }

namespace Microsoft.CodeAnalysis.Emit.EditAndContinue { }

namespace Microsoft.CodeAnalysis.Emit.NoPia { }

namespace Microsoft.CodeAnalysis.ErrorLogger { }

namespace Microsoft.CodeAnalysis.ErrorReporting { }

namespace Microsoft.CodeAnalysis.Extensions { }

namespace Microsoft.CodeAnalysis.ExternalAccess { }

namespace Microsoft.CodeAnalysis.ExternalAccess.Pythia { }

namespace Microsoft.CodeAnalysis.ExternalAccess.Pythia.Api { }

namespace Microsoft.CodeAnalysis.ExternalAccess.UnitTesting { }

namespace Microsoft.CodeAnalysis.ExternalAccess.UnitTesting.Api { }

namespace Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript { }

namespace Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript.Api { }

namespace Microsoft.CodeAnalysis.ExtractMethod { }

namespace Microsoft.CodeAnalysis.FindSymbols { }

namespace Microsoft.CodeAnalysis.FindSymbols.FindReferences { }

namespace Microsoft.CodeAnalysis.FindSymbols.Finders { }

namespace Microsoft.CodeAnalysis.FindSymbols.SymbolTree { }

namespace Microsoft.CodeAnalysis.FlowAnalysis { }

namespace Microsoft.CodeAnalysis.FlowAnalysis.SymbolUsageAnalysis { }

namespace Microsoft.CodeAnalysis.Formatting { }

namespace Microsoft.CodeAnalysis.Formatting.Rules { }

namespace Microsoft.CodeAnalysis.GeneratedCodeRecognition { }

namespace Microsoft.CodeAnalysis.Host { }

namespace Microsoft.CodeAnalysis.Host.Mef { }

namespace Microsoft.CodeAnalysis.Indentation { }

namespace Microsoft.CodeAnalysis.InitializeParameter { }

namespace Microsoft.CodeAnalysis.Internal { }

namespace Microsoft.CodeAnalysis.Internal.Log { }

namespace Microsoft.CodeAnalysis.InternalUtilities { }

namespace Microsoft.CodeAnalysis.Interop { }

namespace Microsoft.CodeAnalysis.LanguageService { }

namespace Microsoft.CodeAnalysis.LanguageService.TypeInferenceService { }

namespace Microsoft.CodeAnalysis.MoveDeclarationNearReference { }

namespace Microsoft.CodeAnalysis.NamingStyles { }

namespace Microsoft.CodeAnalysis.Notification { }

namespace Microsoft.CodeAnalysis.ObsoleteSymbol { }

namespace Microsoft.CodeAnalysis.Operations { }

namespace Microsoft.CodeAnalysis.Options { }

namespace Microsoft.CodeAnalysis.OrganizeImports { }

namespace Microsoft.CodeAnalysis.Packaging { }

namespace Microsoft.CodeAnalysis.PatternMatching { }

namespace Microsoft.CodeAnalysis.PooledObjects { }

namespace Microsoft.CodeAnalysis.Precedence { }

namespace Microsoft.CodeAnalysis.Progress { }

namespace Microsoft.CodeAnalysis.ProjectSystem { }

namespace Microsoft.CodeAnalysis.ReassignedVariable { }

namespace Microsoft.CodeAnalysis.Recommendations { }

namespace Microsoft.CodeAnalysis.Remote { }

namespace Microsoft.CodeAnalysis.RemoveUnnecessaryImports { }

namespace Microsoft.CodeAnalysis.Rename { }

namespace Microsoft.CodeAnalysis.Rename.ConflictEngine { }

namespace Microsoft.CodeAnalysis.ReplaceDiscardDeclarationsWithAssignments { }

namespace Microsoft.CodeAnalysis.RuntimeMembers { }

namespace Microsoft.CodeAnalysis.SQLite { }

namespace Microsoft.CodeAnalysis.SQLite.Interop { }

namespace Microsoft.CodeAnalysis.SQLite.v2 { }

namespace Microsoft.CodeAnalysis.SQLite.v2.Interop { }

namespace Microsoft.CodeAnalysis.SemanticModelReuse { }

namespace Microsoft.CodeAnalysis.Serialization { }

namespace Microsoft.CodeAnalysis.Shared { }

namespace Microsoft.CodeAnalysis.Shared.CodeStyle { }

namespace Microsoft.CodeAnalysis.Shared.Collections { }

namespace Microsoft.CodeAnalysis.Shared.Extensions { }

namespace Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery { }

namespace Microsoft.CodeAnalysis.Shared.Helpers { }

namespace Microsoft.CodeAnalysis.Shared.Helpers.RemoveUnnecessaryImports { }

namespace Microsoft.CodeAnalysis.Shared.Naming { }

namespace Microsoft.CodeAnalysis.Shared.TestHooks { }

namespace Microsoft.CodeAnalysis.Shared.Utilities { }

namespace Microsoft.CodeAnalysis.Simplification { }

namespace Microsoft.CodeAnalysis.Simplification.Simplifiers { }

namespace Microsoft.CodeAnalysis.SolutionCrawler { }

namespace Microsoft.CodeAnalysis.SourceGeneration { }

namespace Microsoft.CodeAnalysis.SourceGeneratorTelemetry { }

namespace Microsoft.CodeAnalysis.Storage { }

namespace Microsoft.CodeAnalysis.SymbolDisplay { }

namespace Microsoft.CodeAnalysis.SymbolSearch { }

namespace Microsoft.CodeAnalysis.Symbols { }

namespace Microsoft.CodeAnalysis.Syntax { }

namespace Microsoft.CodeAnalysis.Syntax.InternalSyntax { }

namespace Microsoft.CodeAnalysis.Tags { }

namespace Microsoft.CodeAnalysis.TaskList { }

namespace Microsoft.CodeAnalysis.Telemetry { }

namespace Microsoft.CodeAnalysis.Text { }

namespace Microsoft.CodeAnalysis.UnitTests { }

namespace Microsoft.CodeAnalysis.Utilities { }

namespace Microsoft.CodeAnalysis.VisualBasic { }

namespace Microsoft.CodeAnalysis.VisualBasic.CodeGeneration { }

namespace Microsoft.CodeAnalysis.VisualBasic.CodeStyle { }

namespace Microsoft.CodeAnalysis.VisualBasic.Formatting { }

namespace Microsoft.CodeAnalysis.VisualBasic.Simplification { }

namespace Microsoft.CodeAnalysis.Workspaces { }

namespace Microsoft.CodeAnalysis.Workspaces.Diagnostics { }

namespace Microsoft.CodeAnalysis.Workspaces.ProjectSystem { }

namespace Microsoft.DiaSymReader { }

namespace Microsoft.SqlServer { }

namespace Microsoft.SqlServer.Server { }

namespace Microsoft.VisualBasic { }

namespace Microsoft.VisualBasic.CompilerServices { }

namespace Microsoft.VisualBasic.FileIO { }

namespace Microsoft.Win32 { }

namespace Microsoft.Win32.SafeHandles { }

namespace Mono { }

namespace Mono.Cecil { }

namespace Mono.Cecil.Cil { }

namespace Mono.Cecil.Metadata { }

namespace Mono.Cecil.PE { }

namespace Mono.Cecil.Pdb { }

namespace Mono.Cecil.Rocks { }

namespace Mono.Collections { }

namespace Mono.Collections.Generic { }

namespace Mono.Security { }

namespace Mono.Security.Cryptography { }

namespace NullGuard { }

namespace NullGuard.CodeAnalysis { }

namespace Roslyn { }

namespace Roslyn.Utilities { }

namespace Scifa { }

namespace Scifa.CheckedExceptions { }

namespace Scifa.CheckedExceptions.Attributes { }

namespace StaticLambda { }

namespace StaticLambda.Fody { }
